#!/bin/bash
# Script to restart services after fixes

echo "================================================================"
echo "🔄 Restarting Services"
echo "================================================================"
echo ""
echo "⚠️  IMPORTANT: The Python service must be restarted to pick up fixes!"
echo ""
echo "1. Stop the Python service in its terminal (Ctrl+C)"
echo "2. Restart it with:"
echo "   cd backend/python-services"
echo "   source venv/bin/activate"
echo "   python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "3. The Node.js backend is fine (no restart needed)"
echo "4. The frontend is fine (Vite HMR handles updates)"
echo ""
echo "================================================================"
echo "🧪 Test After Restart"
echo "================================================================"
echo ""
echo "Medical Face Scanner:"
echo "  - Open browser: http://localhost:3000"
echo "  - Go to Medical Face Scanner tab"
echo "  - Click 'Start Medical Scan'"
echo "  - Should work without 500 errors!"
echo ""
echo "Heart Rate Monitor:"
echo "  - Go to Heart Rate Monitoring tab"
echo "  - Click 'Start Monitoring'"
echo "  - Backend should show: '✅ CAIRE WebSocket connected'"
echo "  - Should work without 'service not ready' errors!"
echo ""
